feat: adds idea board app with some challanges
contentcal-org/ccal-tech-test pull request #2
Opened 2021-03-23 12:05 UTC by gwidonw

![idea-board-login](https://user-images.githubusercontent.com/8656036/112143524-46165e80-8bd8-11eb-9935-f7d867e07398.png)
![idea-board](https://user-images.githubusercontent.com/8656036/112143530-47478b80-8bd8-11eb-9747-1ce0814fc942.png)
![idea-board-editor](https://user-images.githubusercontent.com/8656036/112143529-47478b80-8bd8-11eb-9b87-e60311a1986c.png)

2021-03-23 14:29 UTC, wojciech-szymanski commented on front-end/README.md
> +One of our clients have hundreds or thousends of great ideas. Printing so long list of idea have very bad inpact on Angular performance.
```suggestion
One of our clients has hundreds or thousands of great ideas. Printing such a long list of ideas has a very bad impact on Angular performance.
```

2021-03-23 14:29 UTC, wojciech-szymanski commented on front-end/README.md
> +if we can easly optimalise this component performance?
```suggestion
if we can easily optimise this component performance?
```

2021-03-23 14:45 UTC, wojciech-szymanski commented on front-end/apps/idea-board/src/app/ideas/_stores/ideas.data.ts
> +    description: 'Coffee break increase developers performance',
```suggestion
    description: 'Coffee break increases developers performance',
```

2021-03-23 14:46 UTC, wojciech-szymanski commented on front-end/apps/idea-board/src/app/ideas/_stores/ideas.data.ts
> +    description: `Let's build mobile app`,
```suggestion
    description: `Let's build a mobile app`,
```

2021-03-23 14:54 UTC, wojciech-szymanski commented on front-end/apps/idea-board/src/styles/ui/_page-header.scss
> +  &__actions {
```suggestion

  &__actions {
```

2021-03-23 14:55 UTC, wojciech-szymanski commented on front-end/apps/idea-board/src/styles/ui/_page-header.scss
> +  &__intro {
```suggestion

  &__intro {
```

2021-03-23 14:55 UTC, wojciech-szymanski commented on front-end/apps/idea-board/src/styles/ui/_toggle.scss
> +  &__checkbox {
```suggestion

  &__checkbox {
```

2021-03-23 14:57 UTC, wojciech-szymanski requested changes
I have spotted some typos to fix and minor 💅 

Otherwise top job 👍

2021-03-24 08:43 UTC, gwidonw commented
> 
> 
> I have spotted some typos to fix and minor 💅
> 
> Otherwise top job 👍

@wojciech-szymanski Many thanks. All suggestions were commited.

2021-03-26 14:13 UTC, wojciech-szymanski approved these changes

2021-03-26 14:14 UTC, merged